[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "argparse",
    "jinja2",
    "prospector",
    "pytest",
    "pytest-cov",
    "attrs",
    "pyfakefs",
]
build-backend = "setuptools.build_meta"
